### ISSUE TITLE
Publish function ignores the retained parameter

### ISSUE THREAD

**Issue by csanz91** [rovale/micro-mqtt#261]
Hi, I have found that all the messages sent using the publish function are retained. 
Looking into the source code I have seen that the retained parameter is ignored and the value 'true' is hardcoded in its place. I guess this is just a small bug and not an intended feature.
            https://github.com/rovale/micro-mqtt/blob/a041972248296ee4e4a606b874b890e66e7bc2c3/espruino/modules/micro-mqtt.js#L300

Regards

**Comment by rovale** [comment]
Wow, that is really not OK! Good catch! 

Also there must be something wrong with the test scenario:
https://github.com/rovale/micro-mqtt/blob/b51b290100e93a1a5c55801fa98e44b22d3c59f8/src/test/Protocol.test.ts#L247
😕 

Would you like to look into this and create a small PR?

If not then I wil pick it up ASAP.

Tonight I plan to install Espruino on some ESP8266 and ESP32 boards. It has been a while since I tried it!

**Comment by rovale** [comment]
Yes! The project got it's first PR be someone who is not a bot! Thanks again!
